services:
  web:
    container_name: F8-fullstack-k13
    image: node:22.9.0
    working_dir: /app/web
    volumes:
      - ./4.Homework-React/Day-02_props-todo-list:/app/web
    ports:
      - '3000:3000'
    command: ['npm', 'run', 'dev']